#!/bin/sh -e

echo "Regenerating test output..."
./prepare
./01_check_rig.sh > ./01_check_rig.out
./02_flash_dfu.sh > ./02_flash_dfu.out
./03_check_lsusb.sh > ./03_check_lsusb.out
./04_check_dfu_lsusb.sh > ./04_check_dfu_lsusb.out
./05_flash_dfu_from_app.sh > ./05_flash_dfu_from_app.out
./06_test_simcards.sh > ./06_test_simcards.out
echo "Reference output regenerated!"
echo ""

